### PR TITLE
Add disjointOrd and disjointOrdBy

### PR DESCRIPTION
**Pull request by zliu41**
When profiling HLint on `cabal/cabal-install/Distribution/Client/Setup.hs` I noticed
```
COST CENTRE MODULE          SRC                            %time %alloc

disjoint    Data.List.Extra src/Data/List/Extra.hs:67:1-33  18.6   14.2
```
i.e. `disjoint` is the most costly function. So this PR adds an `n log n` version (more precisely, `(m+n) log (min (m, n))`). This speeds up HLint on `Setup.hs` by about 10%.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Looks like a great idea.

The optimisation to flip the argument order based on the shortest means that the order of the result changes based on length, which is likely to surprise people. If we can't make that robust, I'd be tempted to give up on the swap optimisation.

**Comment by zliu41** [comment]
@ndmitchell Do you mean if one of the lists contains `undefined` or is infinite? Otherwise the result is always the same with vs. without the swap optimization.

In the presence of `undefined` or infinite list, I think the swap optimization makes the result _more_ stable because `disjointOrd xs ys` is _usually_ the same as `disjointOrd ys xs` (unless `length xs == length ys`), which seems more desirable.

If we want `disjointOrd xs ys` to always be the same as `disjointOrd ys xs`, we can implement it similar to: `Set.disjoint (Set.fromList xs) (Set.fromList ys)`, i.e., build the tree on both lists, if `length xs == length ys`. Would you prefer to do this?

By the way, this reminds me that `disjointOrd` is more strict than `disjoint` - I'll add a note in the doc.

**Comment by ndmitchell** [comment]
My bad, I forgot `disjoint` was a predicate, and thus the resulting `Bool` has no knowledge of its order. Thanks!

**Comment by ndmitchell** [comment]
I released 1.7.3.

**Pull request merged**
