### PR TITLE
Add zipDefaultWith

### PR DESCRIPTION
**Pull request by 3noch**
Implementation taken from https://stackoverflow.com/a/43312255/503377

When I found myself copying this from StackOverflow I knew it was time to make a PR to `extra`. :D But maybe it's already somewhere else and I haven't found it.

### CODE REVIEW

**Comment by ndmitchell** [comment]
It seems there should be a package for all the zip combinations people want - error on mismatch, extend, Nothing, a default value. I'm a bit hesitant about this patch for a few reasons:

* The name doesn't quite imply what it does. Default could mean a few things.
* Why not `zipWithFoo :: (Maybe a -> Maybe b -> c)` ?
* Should `Foo` be `Extend`? It's not quite right. I have no idea what it should be.
* Is this the useful version of the combinator? It's not one I've ever gone for or wanted, but that may be because it wasn't available - it's hard to tell in advance.

(And sorry for the delay in replying - caught COVID and have been recovering and getting back to normal.)

**Comment by 3noch** [comment]
I'd welcome a more general version. Other languages call this `zip_longest`.

**Comment by 3noch** [comment]
I'm very sorry to hear about COVID. Glad you're recovering!

**Comment by ndmitchell** [comment]
Looking at Python, they take a single default value, and use it for both lists - the advantage of an untyped language - there's something somewhat unpleasant about passing two defaults, with the knowledge that at most one will ever be used.

Looking at Rust, they have essentially `zipWithLongest :: (Maybe a -> Maybe b -> c) -> [a] -> [b] -> [c]`. I prefer that type, although note that `zipWithLongest :: (These a b -> c) -> [a] -> [b] -> [c]` is a more accurate type, using [These](https://hackage.haskell.org/package/these-1.0.1/docs/Data-These.html).

**Comment by 3noch** [comment]
How do you feel about a new dependency on `these`?

**Comment by 3noch** [comment]
I could also define a type just for this function that is analogous to `These`. Or...use anonymous sums... heh

**Comment by ndmitchell** [comment]
For the extra library, definitely not, as its number of dependencies is deliberately very low. That said, it doesn't seem unreasonable for these to be in base, so if that happened, then it would be fine.

**Comment by ndmitchell** [comment]
I suspect that a pair of Maybe's and a stated invariant is probably the pragmatic way - new data types need functor instances etc, and then it's competing with these library. Seems like a lot of surface area to the library for insufficient benefit.

**Comment by 3noch** [comment]
Yes agreed.

**Comment by ndmitchell** [comment]
So we've landed on `zipWithLongest :: (Maybe a -> Maybe b -> c) -> [a] -> [b] -> [c]` as a signature and prototype? I'm fine with that.

**Comment by ndmitchell** [comment]
I added `zipWithLongest` so am closing this PR.

**Comment by 3noch** [comment]
Thanks. I'm OOO for a bit and wasn't able to get to this.

**Pull request closed without merging**
