### PR TITLE
Add (!?) function

### PR DESCRIPTION
**Pull request by Boarders**
Thanks for the pull request!

By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.

If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.

### CODE REVIEW

**Comment by Boarders** [comment]
I coped the implementation of `(!!)` from `GHC.List` but I also benchmarked it against the naive thing you would write and both had identical performance (I think/assume the GHC version is more like to fuse).

**Comment by Boarders** [comment]
Sorry, I am unsure what the failing CI means here.

**Comment by Boarders** [comment]
Apologies for the CI fails, I edited the `TestGen` file that states at the top `DO NOT MODIFY` 🙂 so I'm not sure if I messed things up somehow.

**Comment by ndmitchell** [comment]
Thanks for the diff! This seems a very reasonable function to add, mirroring that already in bytestring with this alias. I'll need to regenerate some files, so will merge it in a few days time when I've got a bit more time.

**Comment by ndmitchell** [comment]
I needed to update the generator too, see the diff above for all that, but now landed.

**Pull request merged**
