### PR TITLE
whenJustM' accepting a default value

### PR DESCRIPTION
**Pull request by pkamenarsky**
Useful when the monadic computation yields a value:

    user <- lookupUser
    userFriends <- whenJustM' user [] $ \user ->
      return $ userFriends user

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for the patch! Please ignore the failing appveyor test suite, it's due to a Stack bug that I fixed recently, but that hasn't yet made it out into a release yet - your code looks fine.

I'm a little wary of just putting a `'` on the end of an identifier to add a default argument. I wonder if this should be `maybeM` and the default should also have a Monad context? In the particular case above it would probably be clearer to write:

    userFriends <- maybe [] userFriends <$> lookupUser

Do you have other examples where you have wanted this?

**Comment by pkamenarsky** [comment]
I was writing too hastily. Of course this combinator only makes sense if the action inside is monadic, like:

  user <- lookupUser
  userFriendCountOfFriends <- whenJustM' user 0 $ \user -> do
    friends <- getUserFriends user
    mapM getFriendCount friends

Is there a `maybeM` somewhere? Something like

  maybeM :: Monad m => m b -> (a -> m b) -> m (Maybe a) -> m b

? Although it's really nice if the lambda is last like in `whenJustM` since it allows for multiline lambdas without the need for `flip` or parens.

**Comment by ndmitchell** [comment]
There is no maybeM, was just thinking about possible alternatives to your function that could be added. But I agree having the lambda last would be nice. Another alternative that @snowleopard has suggested in the past is:

    whenJust_Monoid :: (Monoid d, Applicative m) => Maybe a -> (a -> m d) -> m d

It's roughly `whenJust' mempty`. Do you think that would be most of your use cases? Or do you think the arbitrary Nothing value is still handy?

**Comment by pkamenarsky** [comment]
I can't think of a case where I'd need `whenJust'` instead of `whenJust_Monoid`, but as you point out `whenJust_Monoid` is a specialized version of `whenJust'` - wouldn't it make more sense to have `whenJust'` then? What about `whenJust_Default" or something?

**Comment by snowleopard** [comment]
> Another alternative that @snowleopard has suggested in the past is:
```haskell
whenJust_Monoid :: (Monoid d, Applicative m) => Maybe a -> (a -> m d) -> m d
```

I actually suggested something like this:
```haskell
when :: (Monoid a, Monad m) => Bool -> m a -> m a
when bool act = if bool then act else return mempty
```
This seems like a natural generalisation of `when :: Monad m => Bool -> m () -> m ()` which doesn't break existing code but makes `when` more powerful, for example:
```haskell
greet exclaim = do
    name <- getLine
    suffix <- when exclaim $ return "!"
    putStrLn $ "Hello, " ++ name ++ suffix
```
Same can be done about `whenM`:
```haskell
whenM :: (Monoid a, Monad m) => m Bool -> m a -> m a
whenM mbool act = do
    bool <- mbool
    if bool then act else return mempty
```
Here is a use-case in Shaking up GHC project (I believe `applyPredicate` is exactly the proposed `whenM`): https://github.com/snowleopard/shaking-up-ghc/blob/master/src/Expression.hs#L90-L94

I don't see any reason for preferring more constrained conventional versions.

**Comment by pkamenarsky** [comment]
This is actually pretty cool. What about generalizing `whenJustM` to having a monoid constraint?

**Comment by snowleopard** [comment]
@pkamenarsky Yes, the same idea should work for `whenJustM`.

However, I've just remembered @ndmitchell's comment on my proposal: why use `Monoid` when all we use is `mempty`? The right constraint to use here may be `Default`, where we can `return def` in the snippets above. This seems to be a cleaner solution from a theoretical standpoint, although in practice I've never seen people using `Default`.

I guess in the right universe we would have something like `Default => Monoid` and then the choice would be obvious.

**Comment by pkamenarsky** [comment]
I agree. I assume you are talking about `data-default`? In that case requiring people to pull another dependency just to use `whenJustM` or `whenM` isn't a good idea I'd say.

**Comment by snowleopard** [comment]
@pkamenarsky Ah, I didn't realise it lives in `data-default`. Agreed, this is not the best approach then.

By the way, another use case for modified `when/whenM`: https://github.com/snowleopard/shaking-up-ghc/blob/34c999b8e9d78b848ef75f8b439b408eafdf7166/src/Rules/Library.hs#L87-L90.
```haskell
exists <- doesDirectoryExist gmpObjects
if exists
then getDirectoryFiles "" [gmpObjects -/- "*.o"]
else return []
```
This could be substituted by either:
```haskell
exists <- doesDirectoryExist gmpObjects
when exists $ getDirectoryFiles "" [gmpObjects -/- "*.o"]
```
or
```haskell
whenM (doesDirectoryExist gmpObjects) $ getDirectoryFiles "" [gmpObjects -/- "*.o"]
```

**Comment by ndmitchell** [comment]
So it sounds like the desire for whenJustM taking an argument argument has mostly gone, and there is a general desire for the when family of functions that return a Monoid. So there seem to be two options:

* Make whenM/whenJust/whenJustM return a Monoid. But then I can't do that for when without a name clash, and then they are inconsistent with when in the Prelude.
* Add when'/when_/whenWithAMonoidDude and similar for each of the alternatives. Any thoughts on a suitable suffix?

Or any other options?

**Comment by snowleopard** [comment]
@ndmitchell If you are prepared to consider `?` as the name for the _family of functions_ then I think we can build on the design I use in Shaking up GHC. It needs time to formulate properly, so if you are interested I will raise a separate issue about this where we could discuss it.

**Comment by pkamenarsky** [comment]
@ndmitchell, @snowleopard: Yes, `when*` returning a monoid covers all use cases I can think of. One possible name scheme (if you don't wanna go with primes) would be something like `whenJustWithDefaultM`, but let's see what @snowleopard comes up with.

**Comment by snowleopard** [comment]
Just to clarify: I didn't mean that the name must necessarily be `?`, it may as well be `whenJustWithDefaultM` or something similar (or both!). It's just that I myself use(d) `?` to play a role very similar to what the `when*` family aims to achieve. I'll put the ideas in writing over the weekend.

**Comment by ndmitchell** [comment]
I'm not super averse to primes here, but have no great ideas in any direction. I wouldn't use `?` in the extra library as it's too useful an operator for way too many things and stealing it seems unfair.

**Comment by snowleopard** [comment]
@ndmitchell Completely agree about `?`. It's very easy for me, or whoever else prefers to use `?` in this context, to simply define `(?) = whenXYZ`.

**Comment by ndmitchell** [comment]
So, to summarise what we've got to so far (please do chime in if you've had any further thoughts since we last discussed this, which was a while ago):

* People often want to "get a result out" of `when` (and the Monadic and Just variants).
* If you don't take the `when` then you need some "default" result, and `mempty` seems like the only reasonable approach.
* Since we can't change `when`, we should probably add a suffix. Using `'` as a suffix isn't good. We don't have a good answer to what that suffix should be yet.

I'm completely lost in a paralysis of choice here. Every option seems reasonable, no option seems compelling...

**Comment by snowleopard** [comment]
Argh, sorry, I meant to write something up, but completely forgot about this.

Anyway, what I recently realised while working on `ApplicativeDo` paper is that we don't need `Monad` for this to work. An `Applicative` seems to be sufficient:
```haskell
condition :: (Applicative f, Monoid a) => f (Bool -> a -> a)
condition = pure $ \b a -> if b then a else mempty

whenA :: (Applicative f, Monoid a) => f Bool -> f a -> f a
whenA fb fa = condition <*> fb <*> fa

main :: IO ()
main = do
    res <- whenA (read <$> getLine) (return ["True"])
    print res
```

In particular, the `?` operator we use in Hadrian can also happily live in an Applicative functor. Thinking of this, indeed, we never alter the structure of our `Args` expressions, we simply erase some parts of a huge sequence (replacing them with `mempty`), which does not require the power of a Monad. 

@ndmitchell I'm not sure if I'm helping or just adding more non-compelling options into consideration... :-)

**Comment by ndmitchell** [comment]
@snowleopard `whenJust` is already an applicative so I'm happy to make things Applicative when they can be. However, I think your definition of `whenA` above is wrong since it evaluates the `return ["True"]` regardless of the condition - I think `whenM` has to be in a Monad to avoid that.

**Comment by snowleopard** [comment]
@ndmitchell Could you clarify what you mean?
Let's change the program slightly:
```haskell
main :: IO ()
main = do
    res <- whenA (read <$> getLine) (return $ undefined ++ ["True"])
    print res
```
Here are some experiments:
```
$ runhaskell whenA.hs
True
whenA.hs: Prelude.undefined

$ runhaskell whenA.hs
False
[]
```
So, we don't evaluate `return $ undefined ++ ["True"]` when the condition is `False`.

**Comment by ndmitchell** [comment]
Try:

    main :: IO ()
    main = do
        res <- whenA (read <$> getLine) (do print "hello"; return ["True"])
        print res

Observe that `hello` gets printed out regardless of whether you enter True or False. You don't evaluate the value if it's False, but you do evaluate the IO.

**Comment by snowleopard** [comment]
@ndmitchell Ah, I see, thanks! Indeed, we need `whenM` to be able to skip side-effects...

**Comment by pkamenarsky** [comment]
So in the meanwhile I've been using `whenJust'` a lot, and there's one frequent use case I came across where a `Monoid` instance isn't enough:

    r <- whenJust' (Left "Invalid user") value $ \value -> do
      ...
      return $ Right Something

This is easily solved with `maybeToEither` or something like that, but I really dislike abusing `Monoid` for "something with a default value". I'd probably go with `whenJust'`.

**Comment by ndmitchell** [comment]
@pkamenarsky so you are really just doing a `maybeM` with the functional argument at the end, not a `when` at all. If you can think of a good name for that I'd be happy to add it. Alternatively, if I just add normal maybeM you could have written:

    r <- maybeM (Left "Invalid user") `flip` value $ \value -> do
      ...
      return $ Right Something

Perhaps in the interest of not inventing new names that's what should be done?

**Comment by pkamenarsky** [comment]
@ndmitchell: `maybeM` sounds absolutely fine to me, and the '`flip`' isn't a problem either! I think that's it :)

**Comment by ndmitchell** [comment]
Awesome - we have an answer! @pkamenarsky - want to update the pull request? If not, I'm happy enough to implement it.

**Comment by pkamenarsky** [comment]
Done :)

**Comment by pkamenarsky** [comment]
Will fix the errors.

**Comment by ndmitchell** [comment]
I see a tags file in that commit. I assume that was a mistake? Do feel free to add a suitable gitignore pattern to avoid it.

**Comment by pkamenarsky** [comment]
Wow, messing up a lot of stuff :) I'm not sure why the PR isn't mergeable anymore (maybe because I removed the `tags` file?).

**Comment by ndmitchell** [comment]
This pull request is accumulating a lot of patches back and forth for quite a small change, so perhaps the easiest way is for me to just copy the meaningful change into the repo and credit you.

For `maybeM` there are actually three signatures that make sense (ignoring the `Applicative`/`Monad` difference):

1. `Monad m =>   b -> (a -> m b) ->   (Maybe a) -> m b`
2. `Monad m => m b -> (a -> m b) ->   (Maybe a) -> m b`
3. `Monad m => m b -> (a -> m b) -> m (Maybe a) -> m b`

Of those, I think 2 is probably the most natural (maybe? or is it 1?) - but you could certainly argue for any of them. @pkamenarsky, was your pull request for 3 based on thats what works best for you? @snowleopard, do you have an opinion?

**Comment by snowleopard** [comment]
@ndmitchell I currently find it hard to have an opinion on this. I looks to me that we are dealing with some extremely ubiquitous pattern, but the structure of this pattern is not obvious.

Just some trivial observations:
* In all instances discussed above the resulting value is wrapped in a (usually monadic) context `m a`.
* We always have some `whenFalse` (default) value, which we take either from a `Monoid` instance or as an explicit parameter (the first parameter in your three `maybeM` cases).
* We always have some `whenTrue` value, which we take as an explicit, possibly wrapped, parameter, which is possibly fed through another given function.
* We always check a Boolean _condition_, which is encoded either by some possibly wrapped `Bool` or by a `Maybe`. Depending on the condition we return `whenFalse` or `whenTrue`.

Some sort of a higher-level `if` statement :-)

**Comment by ndmitchell** [comment]
Yeah, I've often noted that Predicates (things returning Bool) sometimes generate evidence of the truthiness of the value, and then end up returning a Maybe instead.

I do observe that all the other higher-order liftings generally make the function monadic but nothing else.

**Comment by ndmitchell** [comment]
Looking back at my 3 options:

* `Monad m => b -> (a -> m b) -> (Maybe a) -> m b` - not consistent with how you'd generalise `either`, so not an option.
* `Monad m => m b -> (a -> m b) -> (Maybe a) -> m b` - the Monad constraint isn't required at all, and in fact this is just `maybe` instantiated with `b ~ m b`. Completely pointless.
* `Monad m => m b -> (a -> m b) -> m (Maybe a) -> m b` - the only logical alternative.

**Comment by ndmitchell** [comment]
Added, and released in extra-1.4.6.

**Pull request closed without merging**
