### PR TITLE
Additions to Control.Exception and Control.Monad.Except

### PR DESCRIPTION
**Pull request by ddssff**
* Add withException and displaySomeExceptionType to Control.Exception.Extra
* Add tryError, withError, and handleError to Control.Monad.Except.Extra,
  see https://github.com/haskell/mtl/issues/60 for discussion.

Thanks for the pull request!

By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.

If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for the patch. However, I'm not sure if extensions to `mtl` really belong in this patch. From what I've seen most people use `transformers` rather than `mtl`, but the very fact there are two "competing" libraries in this space makes me think `extra` shouldn't push people towards either of them.

Regarding the others, I'm not sure I see a massive use for `withException`, and it has quite a complex type, so I'm inclined to avoid it. It feels like `displaySomeExceptionType` might be better called `typeOfException`? And returning a `TypeRep`, from which it's easy enough to `show` it.

**Comment by ddssff** [comment]
Not a problem if these are not of interest.  displaySomeExceptionType name is patterned after the displayException function, which for some reason I thought was named displaySomeException.  I didn't realize mtl was deprecated, does transformers provide an equivalent to MonadError?

**Comment by ndmitchell** [comment]
I wouldn't say mtl is deprecated, just that most people use Transformers. I've never really used the MonadError part, so have no idea what it provides there. https://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Error.html suggests to use Trans.Except instead, which is probably worth investigating.

**Comment by ndmitchell** [comment]
Why go all the way to showing the type? Wouldn't it be more useful to get the exception type, and then if you want, `show` to get it as a `String`, but if you don't want, compare it to a known type?

**Comment by infinity0** [comment]
It is confusing at first, but AIUI mtl complements and extends transformers - transformers are the basic concrete types, whereas mtl provides typeclasses so you can perform e.g. `Writer` operations with arbitrary transformers stacked on top, in cases where you can't be bothered lifting the precise number of times, or where you want to write code that works in unknown transformers.

That all sounds good, but the downside of mtl is that the typeclass resolution can get very confusing, partly because GHC's error messages aren't very detailed about how it's attempting to resolve classes. Also the resolution fails when you have multiple versions of the transformer (e.g. StateT) in a stack. Also there are missing instances e.g. https://github.com/haskell/mtl/issues/69 for some of the newer transformers classes. I generally find transformers much easier to work with and reason about for application code, whereas mtl can be useful for library code - e.g. lens builds on top of `MonadState`.

I would suggest adding the mtl-specific functions to mtl itself instead.

**Comment by ndmitchell** [comment]
Yep, these should go towards `mtl`. It's really hard to get things into `base`, so `extra` is a good stopgap, but it really should just stick to `base` to a first approximation (with a few useful exceptions, e.g. `process`).

**Pull request closed without merging**
